mini-video/apps/home/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, SubmitField, PasswordField, FileField, TextAreaField
from wtforms.validators import DataRequired, EqualTo, Email, Regexp, ValidationError
from apps.models import User


class RegisterForm(FlaskForm):
    name = StringField(
        label='昵称',
        validators=[
            DataRequired("请输入昵称!"),
        ],
        description="昵称",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入昵称",
            "required": "required"
        }
    )

    email = StringField(
        label='邮箱',
        validators=[
            DataRequired("请输入邮箱"),
            Email("请输入正确的邮箱格式")
        ],
        description="邮箱",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入邮箱",
            "required": "required"
        }
    )

    phone = StringField(
        label="手机",
        validators=[
            DataRequired("请输入昵称!"),
            Regexp(r"1[34578]\d{9}", message="手机格式不正确")
        ],
        description="手机",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入手机号码",
            "required": "required"
        }
    )

    pwd = PasswordField(
        label='密码',
        validators=[
            DataRequired("请输入密码!")
        ],
        description="密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入密码",
            "required": "required"
        }
    )

    repwd = PasswordField(
        label='确认密码',
        validators=[
            DataRequired("请再次输入密码!"),
            EqualTo("pwd", "密码不一致")
        ],
        description="确认密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请确认密码",
            "required": "required"
        }
    )
    submit = SubmitField(
        "注册",
        render_kw={
            "class": "btn btn-lg btn-success btn-block"
        }
    )

    def validate_name(self, field):
        name = field.data
        user = User.query.filter_by(name=name).count()
        if user:
            raise ValidationError("昵称已被注册")

    def validate_email(self, field):
        email = field.data
        user = User.query.filter_by(email=email).count()
        if user:
            raise ValidationError("邮箱已被注册")

    def validate_phone(self, field):
        phone = field.data
        user = User.query.filter_by(phone=phone).count()
        if user:
            raise ValidationError("手机号码已被注册")


class LoginForm(FlaskForm):
    account = StringField(
        label="账号",
        validators=[
            DataRequired("请输入账号!"),
        ],
        description="账号",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "用户名/邮箱/手机号码",
            "required": "required"
        }
    )

    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码!"),
        ],
        description="密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入密码",
            "required": "required"
        }
    )

    submit = SubmitField(
        "登录",
        render_kw={
            "class": "btn btn-lg btn-success btn-block"
        }
    )


class UserDetailForm(FlaskForm):
    name = StringField(
        label='昵称',
        validators=[
            DataRequired("请输入昵称!"),
        ],
        description="昵称",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入昵称",
            "required": "required"
        }
    )

    email = StringField(
        label='邮箱',
        validators=[
            DataRequired("请输入邮箱"),
            Email("请输入正确的邮箱格式")
        ],
        description="邮箱",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入邮箱",
            "required": "required"
        }
    )

    phone = StringField(
        label="手机",
        validators=[
            DataRequired("请输入昵称!"),
            Regexp(r"1[34578]\d{9}", message="手机格式不正确")
        ],
        description="手机",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入手机号码",
            "required": "required"
        }
    )

    face = FileField(
        label="头像",
        validators=[
            DataRequired("请上传头像!")
        ],
        description="头像",
        render_kw={
            "id": "input_face"
        }
    )

    info = TextAreaField(
        label="简介",
        description="简介",
        render_kw={
            "class": "form-control",
            "rows": 10,
        }
    )

    submit = SubmitField(
        "保存修改",
        render_kw={
            "class": "btn btn-success"
        }
    )


class PwdForm(FlaskForm):
    old_pwd = PasswordField(
        label='原密码',
        validators=[
            DataRequired("请输入原密码!")
        ],
        description="原密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入原密码",
            "required": "required",
            "id": "input_oldpwd"
        }
    )
    new_pwd = PasswordField(
        label='新密码',
        validators=[
            DataRequired("请输入新密码!")
        ],
        description="新密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "请输入新密码",
            "required": "required",
            "id": "input_newpwd"
        }
    )

    submit = SubmitField(
        "修改",
        render_kw={
            "class": "btn btn-success btn-lg"
        }
    )


class CommentForm(FlaskForm):
    content = TextAreaField(
        label="内容",
        validators=[
            DataRequired("请填写评论内容!")
        ],
        description="评论内容",
        render_kw={
            "id": "input_content"
        }
    )

    submit = SubmitField(
        "提交评论",
        render_kw={
            "class": "btn btn-success",
            "id": "btn-sub"
        }
    )

mini-video/apps/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

import apps.home.views

mini-video/apps/home/views.py
import os
import uuid

from apps import app
from . import home
from flask import render_template, redirect, url_for, flash, session, request
from werkzeug.security import generate_password_hash
from .forms import RegisterForm, LoginForm, UserDetailForm, PwdForm, CommentForm
from functools import wraps
from apps.models import User, UserLog, Preview, Tag, Movie, Comment, Moviecol
from apps import db
from werkzeug.utils import secure_filename
from apps.admin.views import change_filename


# 登录需求装饰器
def user_login_req(func):
    @wraps(func)
    def decorated_function(*args, **kwargs):
        if "user" not in session:
            return redirect(url_for("home.login", next=request.url))
        return func(*args, **kwargs)
    return decorated_function


# 会员登录
@home.route('/login/', methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name=data["account"]).first()
        if not user:
            flash("用户还未注册", "err")
            return redirect(url_for("home.login"))
        if not user.check_pwd(data["pwd"]):
            flash("密码错误", "err")
            return redirect(url_for("home.login"))
        session["user"] = user.name
        session["user_id"] = user.id

        # 存入登录日志
        user_log = UserLog(
            user_id=user.id,
            ip=request.remote_addr
        )
        db.session.add(user_log)
        db.session.commit()

        return redirect(url_for("home.index", page=1))
    return render_template('home/login.html', form=form)


# 会员注销
@home.route('/logout/')
@user_login_req
def logout():
    session.pop("user", None)
    session.pop("user_id", None)
    return redirect(url_for("home.login"))


# 会员注册
@home.route('/register/', methods=["GET", "POST"])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        data = form.data
        user = User(
            name=data["name"],
            pwd=generate_password_hash(data["pwd"]),
            email=data["email"],
            phone=data["phone"],
            uuid=uuid.uuid4().hex
        )
        db.session.add(user)
        db.session.commit()
        flash("注册成功,请登录!", "ok")
        return redirect(url_for("home.login"))
    return render_template("home/register.html", form=form)


# 会员中心
@home.route('/user/', methods=["GET", "POST"])
@user_login_req
def user():
    form = UserDetailForm()
    user = User.query.get(session["user_id"])
    form.face.validators = []
    if request.method == "GET":
        form.name.data = user.name
        form.email.data = user.email
        form.phone.data = user.phone
        form.info.data = user.info
    if form.validate_on_submit():
        data = form.data
        if form.face.data.filename:
            # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!enctype = "multipart/form-data"
            file_face = secure_filename(form.face.data.filename)

            face_dir = os.path.join(app.config["UP_DIR"], "user")

            if not os.path.exists(face_dir):
                os.makedirs(face_dir)
                os.chmod(face_dir, "rw")
            user.face = change_filename(file_face)
            form.face.data.save(os.path.join(face_dir, user.face))

        # 昵称,邮箱,手机号码唯一性判断STAR
        name_count = User.query.filter_by(name=data["name"]).count()
        if data["name"] != user.name and name_count == 1:
            flash("昵称已经存在", "err")
            return redirect(url_for("home.user"))
        email_count = User.query.filter_by(email=data["email"]).count()
        if data["email"] != user.email and email_count == 1:
            flash("邮箱已被注册", "err")
            return redirect(url_for("home.user"))
        phone_count = User.query.filter_by(phone=data["phone"]).count()
        if data['phone'] != user.phone and phone_count == 1:
            flash("手机号已被注册", "err")
            return redirect(url_for("home.user"))
        # 唯一性判断END

        user.name = data["name"]
        user.email = data["email"]
        user.phone = data["phone"]
        user.info = data["info"]
        db.session.commit()
        flash("修改成功", "ok")
        return redirect(url_for("home.user"))
    return render_template("home/user.html", form=form, user=user)


# 修改密码
@home.route('/pwd/', methods=["GET", "POST"])
@user_login_req
def pwd():
    form = PwdForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.get(session["user_id"])
        if not user.check_pwd(data["old_pwd"]):
            flash("原密码错误!", "err")
            return redirect(url_for("home.pwd"))
        user.pwd = generate_password_hash(data["new_pwd"])
        db.session.commit()
        flash("修改密码成功, 请重新登录", "ok")
        session.pop("user", None)
        session.pop("user_id", None)
        return redirect(url_for("home.login"))
    return render_template("home/pwd.html", form=form)


# 评论记录
@home.route('/comments/<int:page>/')
@user_login_req
def comments(page=1):
    page_data = Comment.query.join(User).filter(
        User.id == Comment.user_id,
        Comment.user_id == session['user_id']
    ).paginate(page=page, per_page=10)
    return render_template('home/comments.html', page_data=page_data)


# 添加电影收藏
@home.route("/moviecol/add/<int:id>", methods=["GET"])
@user_login_req
def moviecol_add(id=None):
    movie = Movie.query.get_or_404(id)
    movie_col = Moviecol(
        movie_id=id,
        user_id=session["user_id"]
    )
    db.session.add(movie_col)
    db.session.commit()
    flash("收藏电影成功", "ok")
    return redirect(url_for("home.play", id=id, page=1))


# 收藏电影
@home.route('/moviecol/<int:page>')
@user_login_req
def moviecol(page=1):
    page_data = Moviecol.query.join(Movie).filter(
        Movie.id == Moviecol.movie_id,
        Moviecol.user_id == session["user_id"]
    ).order_by(
        Moviecol.add_time.desc()
    ).paginate(page=page, per_page=10)
    return render_template('home/moviecol.html', page_data=page_data)


# 登录日志
@home.route('/loginlog/<int:page>/', methods=["GET", "POST"])
@user_login_req
def login_log(page=None):
    if not page:
        page = 1
    page_data = UserLog.query.filter_by(
        user_id=session["user_id"]
    ).order_by(
        UserLog.add_time.desc()
    ).paginate(page=page, per_page=10)
    return render_template('home/loginlog.html', page_data=page_data)


# 首页
@home.route("/", methods=["GET"])
def first():
    return redirect(url_for("home.index", page=1))


@home.route('/<int:page>/', methods=["GET"])
def index(page=1):
    tags = Tag.query.all()
    tid = request.args.get("tid", 0)

    page_data = Movie.query
    if int(tid):
        page_data = page_data.filter_by(tag_id=int(tid))
    star = request.args.get("star", 0)
    if int(star):
        page_data = page_data.filter_by(star=int(star))
    # if not int(tid) and not int(star):
    #     page_data = page_data.all()
    time = request.args.get("time", 0)
    if int(time):
        if int(time) == 1:
            page_data = page_data.order_by(
                Movie.add_time.desc()
            )
        else:
            page_data = page_data.order_by(
                Movie.add_time.desc()
            )
    pm = request.args.get("pm", 0)
    if int(pm):
        if int(time) == 1:
            page_data = page_data.order_by(
                Movie.play_num.desc()
            )
        else:
            page_data = page_data.order_by(
                Movie.play_num.desc()
            )
    cm = request.args.get("cm", 0)
    if int(cm):
        if int(time) == 1:
            page_data = page_data.order_by(
                Movie.comment_num.desc()
            )
        else:
            page_data = page_data.order_by(
                Movie.comment_num.desc()
            )

    p = dict(
        tid=tid,
        star=star,
        time=time,
        pm=pm,
        cm=cm
    )
    page_data = page_data.paginate(page=page, per_page=12)
    return render_template('home/index.html', tags=tags, p=p, page_data=page_data)


# 上映预告轮播图
@home.route('/animation/', methods=["GET"])
def animation():
    data = Preview.query.all()
    return render_template('home/animation.html', data=data)


# 查找
@home.route('/search/<int:page>/', methods=["GET"])
def search(page=1):
    key = request.args.get("key", "")
    page_data = Movie.query.filter(
        Movie.title.ilike("%" + key + "%")
    ).order_by(
        Movie.add_time.desc()
    ).paginate(page=page, per_page=10)
    nums = len(page_data.items)
    return render_template('home/search.html', key=key, nums=nums, page_data=page_data)


# 播放电影
@home.route('/play/<int:id>/<int:page>', methods=["GET", "POST"])
def play(id=None, page=1):
    form = CommentForm()
    movie = Movie.query.join(Tag).filter(
        Tag.id == Movie.tag_id,
        Movie.id == id
    ).first_or_404()
    if request.method == "GET":
        movie.play_num += 1
    if session["user"] and form.validate_on_submit():
        data = form.data
        comment = Comment(
            content=data["content"],
            movie_id=id,
            user_id=session["user_id"]
        )
        db.session.add(comment)
        movie.comment_num += 1
        db.session.commit()
        flash("发表评论成功", "ok")
        return redirect(url_for("home.play", id=id, page=page))
    db.session.commit()

    page_data = Comment.query.join(Movie).join(User).filter(
        Movie.id == Comment.movie_id,
        User.id == Comment.user_id,
        Movie.id == id
    )
    comment_num = page_data.count()
    page_data = page_data.order_by(Comment.add_time.desc()).paginate(page=page, per_page=5)

    return render_template('home/play.html', movie=movie, form=form, page_data=page_data, comment_num=comment_num)

mini-video/apps/templates/home/animation.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>热映电影</title>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='anim/css/style.css') }}">
</head>
<body>
<!--轮播图 开始 -->
<div class="main_banner">
	<div class="main_banner_wrap">
		<canvas id="myCanvas" width="150" height="150"></canvas>
		<div class="main_banner_box" id="m_box">
			<a href="javascript:void(0)" class="banner_btn js_pre">
				<span class="banner_btn_arrow"><i></i></span>
			</a>
			<a href="javascript:void(0)" class="banner_btn btn_next js_next">
				<span class="banner_btn_arrow"><i></i></span>
			</a>
			<ul>
                {% for item in data %}
				<li id="imgCard{{ item.id - 1 }}">
					<a href=""><span style="opacity:0.4;"></span></a>
					<img src="{{ url_for('static', filename="uploads/" + item.logo) }}" alt="">
					<p>{{ item.title }}</p>
				</li>
                {% endfor %}
			</ul>
			<!--火狐倒影图层-->
			<p id="rflt"></p>
			<!--火狐倒影图层-->
		</div>
		<!--序列号按钮-->
		<div class="btn_list">
			<span class="curr"></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
		</div>
	</div>

</div>
<!--轮播图 结束 -->

<script type="text/javascript" src="{{ url_for('static',filename='anim/js/jquery.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='anim/js/script.js') }}"></script>

</body>
</html>

mini-video/apps/templates/home/home.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap-movie.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/animate.css') }}">
    <style>
        .navbar-brand>img {
            display: inline;
        }
        .media{
            padding:3px;
            border:1px solid #ccc
        }

    </style>
    {% block css %}{% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('home.index', page=1) }}" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static', filename='base/images/logo.png') }}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！" id="key_movie">
                    <span class="input-group-btn">
                        <a class="btn btn-default" id="do_search"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for('home.index', page=1) }}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.login') }}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.register') }}"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.logout') }}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for("home.user") }}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
{% block content %}
{% endblock %}
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2017&nbsp;flaskmovie.imooc.com&nbsp;京ICP备 13046642号-2
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for('static', filename='base/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/jquery.singlePageNav.min.js') }}"></script>
<script src="{{ url_for('static', filename='base/js/wow.min.js') }}"></script>
<script src="{{ url_for('static', filename='lazyload/jquery.lazyload.min.js') }}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function() {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function() {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
        $("#do_search").click(function(){
            var key = $("#key_movie").val();
            location.href = "{{ url_for("home.search", page=1) }}?key=" + key;
            }
        );
    });

</script>
{% block js %}{% endblock %}
</body>
</html>

mini-video/apps/templates/home/index.html
{% extends "home/home.html" %}
{% import "UI/admin_page.html" as pg %}
{% block content %}
<section id="hotmovie" style="margin-top:76px">
    <div class="container">
        <div class="row wow fadeInRight" data-wow-delay="0.6s">
            <div class="row">
                <iframe class="wow fadeIn" width="100%" height="375px" frameborder=0 scrolling=no src="{{ url_for('home.animation') }}"></iframe>
            </div>
        </div>
    </div>
</section>
<!--热门电影-->
<!--电影列表-->
<section id="movielist">
    <div class="container">
        <div class="row wow fadeIn" data-wow-delay="0.6s">
            <div class="col-md-12 table-responsive">
                <table class="table text-left table-bordered" id="movietags">
                    <tr>
                        <td style="width:10%;">电影标签</td>
                        <td style="width:90%;">
                            {% for tag in tags %}
                            <a href="{{ url_for('home.index', page=1) }}?tid={{ tag.id }}&star={{ p['star'] }}&time={{ p['time'] }}&pm={{ p["pm"] }}&cm={{ p["cm"] }}" class="label label-info"><span class="glyphicon glyphicon-tag"></span>&nbsp;{{ tag.name }}</a>
                            &nbsp;
                        {% endfor %}

                    </tr>
                    <tr>
                        <td>电影星级</td>
                        <td>
                            {% for index in range(1,6) %}
                            <a href="{{ url_for('home.index', page=1) }}?tid={{ p['tid'] }}&star={{ index }}&time={{ p['time'] }}&pm={{ p["pm"] }}&cm={{ p["cm"] }}" class="label label-warning"><span class="glyphicon glyphicon-star"></span>&nbsp;{{ index }}星</a>
                            &nbsp;
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <td>上映时间</td>
                        <td>
                            <a href="{{ url_for('home.index', page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time=1&pm={{ p['pm'] }}&cm={{ p['cm'] }}" class="label label-default"><span class="glyphicon glyphicon-time">&nbsp;从早到晚</span> </a>
                            &nbsp;
                            <a href="{{ url_for('home.index', page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time=2&pm={{ p['pm'] }}&cm={{ p['cm'] }}" class="label label-default"><span class="glyphicon glyphicon-time">&nbsp;从晚到早</span> </a>
                            &nbsp;
                        </td>
                    </tr>
                    <tr>
                        <td>播放数量</td>
                        <td>
                            <a href="{{ url_for('home.index', page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm=1&cm={{ p['cm'] }}" class="label label-success"><span class="glyphicon glyphicon-arrow-down">&nbsp;从高到底</span></a>
                            &nbsp;
                            <a href="{{ url_for('home.index', page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm=2&cm={{ p['cm'] }}" class="label label-danger"><span class="glyphicon glyphicon-arrow-up">&nbsp;从低到高</span></a>
                        </td>
                    </tr>
                    <tr>
                        <td>评论数量</td>
                        <td>
                            <a href="{{ url_for('home.index', page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm={{ p['pm'] }}&cm=1" class="label label-success"><span class="glyphicon glyphicon-arrow-down">&nbsp;从高到底</span></a>
                            &nbsp;
                            <a href="{{ url_for('home.index', page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm={{ p['pm'] }}&cm=2" class="label label-danger"><span class="glyphicon glyphicon-arrow-up">&nbsp;从低到高</span></a>
                        </td>
                    </tr>
                </table>
            </div>
            {% for movie in page_data.items %}
            <div class="col-md-3">
                <div class="movielist text-center">
                    <!--<img data-original="holder.js/262x166"
                             class="img-responsive lazy center-block" alt="">-->
                    <img src="{{ url_for("static", filename="uploads/" + movie.logo) }}" class="img-responsive center-block" alt="">
                    <div class="text-left" style="margin-left:auto;margin-right:auto;width:210px;">
                        <span style="color:#999;font-style: italic;">{{ movie.titel }}</span><br>
                        <div>
                            {% for index in range(movie.star) %}
                            <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                            {% endfor %}
                        </div>
                    </div>
                    <a href="{{ url_for('home.play',id=movie.id,page=1) }}" class="btn btn-primary" target="_blank" role="button"><span class="glyphicon glyphicon-play"></span>&nbsp;播放</a>
                </div>
            </div>
            {% endfor %}

            <div class="col-md-12">
                <nav aria-label="Page navigation">
                    {{ pg.page(page_data,'home.login_log') }}
                </nav>
            </div>
        </div>
    </div>
</section>
<!--电影列表-->
{% endblock %}

mini-video/apps/templates/home/menu.html
<div class="col-md-3">
        <div class="list-group">
            <a id="m-1" href="{{ url_for('home.user') }}" class="list-group-item">
                <span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
            </a>
             <a id="m-2" href="{{ url_for('home.pwd') }}" class="list-group-item">
                <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
            </a>
            <a id="m-3" href="{{ url_for('home.comments', page=1) }}" class="list-group-item">
                <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
            </a>
            <a id="m-4" href="{{ url_for('home.login_log', page=1) }}" class="list-group-item">
                <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
            </a>
            <a id="m-5" href="{{ url_for('home.moviecol', page=1) }}" class="list-group-item">
                <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏电影
            </a>
        </div>
    </div>